apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls
  namespace: dev
spec:
  secretName: wildcard-tls-secret
  issuerRef:
    name: letsencrypt-prod-dns # Only DNS-01 supports wildcard certificates
    kind: ClusterIssuer
  dnsNames:
  - "wildcard.infratestapp.pp.ua" # Wildcard for all subdomains
