apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wildcard-https-route
  namespace: dev
spec:
  parentRefs:
  - name: wildcard-gateway
    namespace: dev
    sectionName: https-listener
  hostnames:
  - "wildcard.infratestapp.pp.ua"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: app-1
      namespace: dev
      port: 5000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wildcard-http-redirect
  namespace: dev
spec:
  parentRefs:
  - name: wildcard-gateway
    namespace: dev
    sectionName: http-listener
  hostnames:
  - "wildcard.infratestapp.pp.ua"
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
